### ISSUE TITLE
all comands from section =CLUBMEMBER= return error

### ISSUE THREAD

**Issue by Td10tsk** [Tau-Coin/taucoin#20]
First of 3 return: ERROR JSON PARSING
4 return simple error with false

**Comment by bilalag** [comment]
I didnt understand your issue, which section of CLUBMEMEBER and commands are you referring to

**Comment by feyrian** [comment]
That's because you didn't provide a valid JSON parameter.
You need to escape quote the address like this:
`taucoin-cli dumpclubmembers \"club-members.json\" 37565`
`taucoin-cli getmemberinfo \"TMVdL357ZRyBw4K76hvPdaQMHtXeht5J9X\" 37565`
`taucoin-cli getminingpowerbyaddress \"TMVdL357ZRyBw4K76hvPdaQMHtXeht5J9X\" 37565`

About getrewardrate check #9

**Comment by feyrian** [comment]
@Td10tsk thanks to close the issue.
